### ISSUE TITLE
@typedef support

### ISSUE THREAD

**Issue by jnewc** [Wikunia/brackets-QuickDocsJS#16]
Would it be possible to add @typedef support?

I'm using enyo and want to use a declaration of the following type:

    /**
     * @typedef MyKindName
     */
    enyo.kind({
        name: "MyKindName"
    });

**Comment by Wikunia** [comment]
Can you give me an whole example? Never worked with stuff like this. So I need an example line where the shortcut `Ctrl-K` should work and how the `Inline Docs` should look like. Maybe you can provide an modified screenshot or sth like that,

**Comment by jnewc** [comment]
Think I may have misunderstood this as running JSDoc on the same code did not produce what I expected.

I think enyo is just not suited to JSDoc unfortunately. When I have more time to experiment I will post back if I find a way to do what I need.
