### ISSUE TITLE
Displays weird with DarkSoda theme

### ISSUE THREAD

**Issue by torreyn** [Wikunia/brackets-QuickDocsJS#18]
![screenshot 2015-03-16 14 19 54](https://cloud.githubusercontent.com/assets/665802/6676799/cdc76e08-cbe7-11e4-9009-2bcce8557953.png)

The text is read and highlighted in a light color when using the DarkSoda theme.

**Comment by Wikunia** [comment]
Sorry for the late response :/
Do you have an idea how it should look like?
That's the look using "Quick Dark"
![brackets-funcdocr- 32](https://cloud.githubusercontent.com/assets/4931746/6858647/fce4d942-d410-11e4-9e73-9e1afcc5babe.png)

**Comment by torreyn** [comment]
The way it looks in Quick Dark or in the default Dark is good. Font style is good, but it should be the same color and background as normal text.

I see in your less file:

`    code {
        font-family: SourceCodePro;
        font-size: 12px;
        color: @emphasized-text-color;
        background: none;   // revert Bootstrap's styling
        padding: 0;
        white-space: normal;
    } `

Maybe get rid of  `color:@emphasized-text-color;`

**Comment by Wikunia** [comment]
At the bottom of the less file you can see a `.dark` block which has an effect on dark themes but any color changes doesn't matter there and I don't know why :/

**Comment by torreyn** [comment]
Actually, I just downloaded your git repository and made that change your less and installed it, and that didn't fix it. Then I downloaded the DarkSoda theme and edited the CSS. So it's their issue not yours. I'll put in an issue with them. Thanks for looking into it :)

This is how it looks when I delete 3 CSS styles:
![screenshot 2015-03-27 10 36 51](https://cloud.githubusercontent.com/assets/665802/6873394/35c969d8-d46d-11e4-8bb7-fedaca293def.png)

**Comment by Wikunia** [comment]
I added some `!important` to my less file and now it should works. I am really not an expert in design stuff. Can you please install it from URL and then I can register it if everything works properly.

**Comment by torreyn** [comment]
Yes! That fixed it! Thank you!

I also put in a pull request from DarkSoda. Let's see if they accept it.

**Comment by Wikunia** [comment]
At the moment I am getting in the register progress so I'll try it at later.
