### ISSUE TITLE
JSDoc missing attributes in the preview screen

### ISSUE THREAD

**Issue by kivervinicius** [Wikunia/brackets-QuickDocsJS#19]
Hello, congrats to awesome extension, but i have a problem, any attributes, how @author, @createDate don't show in preview screen... why?

![image](https://cloud.githubusercontent.com/assets/4115328/7067023/1014547c-de96-11e4-8664-2eaef1ad136b.png)

**Comment by Wikunia** [comment]
Well short answer: It's not implemented :D But yes I will think about it. Do you have a design suggestion?

**Comment by kivervinicius** [comment]
:smile: i will think about this.

**Comment by Wikunia** [comment]
Any ideas? :) Sorry I have a lot to do at the moment, but I would like to implement it!

**Comment by kivervinicius** [comment]
I'm sorry too, but I will think about it soon. :+1:

**Comment by Wikunia** [comment]
At the right side of the title `author` and then `lastmodifiedDate (creationDate)` so it's easy to see the last modification date and if necessary the creation Date. Or the author under the function name... :)

**Comment by Wikunia** [comment]
![brackets-quickdocsjs-19](https://cloud.githubusercontent.com/assets/4931746/7551386/833969d0-f686-11e4-8ad9-de3eee1ebaee.png)
Don't like it :D do you have a better idea?

**Comment by Wikunia** [comment]
And don't know how to differentiate between `lastmodifiedBy` and `author` :/

**Comment by kivervinicius** [comment]
Well i like, the important is the information,  do you can differentiate this on descriptions same, well i believe it

**Comment by Wikunia** [comment]
What do you think about this one?
![issue_19](https://cloud.githubusercontent.com/assets/4931746/7566911/f8acec90-f7f9-11e4-94d6-8312dcc64e7f.png)

**Comment by kivervinicius** [comment]
That's awesome, resolved all the problems

**Comment by kivervinicius** [comment]
Do you visit this http://usejsdoc.org/index.html? All tags are explained here, we can add to the plugin also

**Comment by kivervinicius** [comment]
:+1:  thanks for all
