### ISSUE TITLE
Doesn't work properly when JSDoc comments hasn't a description

### ISSUE THREAD

**Issue by jcbp** [Wikunia/brackets-QuickDocsJS#21]
Example

```javascript
var Num = {
	/**
	 * @param {number} numA
	 * @param {number} numB
	 */
	isEqual: function(numA, numB) {
		return numA === numB;
	}
};
```
The first parameter is shown as description.

**Comment by Wikunia** [comment]
Thanks for the issue ;)
Can you try to install from URL before I register the new version?

**Comment by jcbp** [comment]
Awasome!
It works perfect.
Thanks for the quick reply.
