### ISSUE TITLE
Bug when using with variables

### ISSUE THREAD

**Issue by Eugene-Musika** [Wikunia/brackets-QuickDocsJS#25]
If I try to use quick docs when the cursor is on some variable, Brackets freezes and usage of processor jumps to 100 percent.

**Comment by Wikunia** [comment]
I'm sorry that I reply that late. I checked it just now and the problem does not appear on my machine and brackets version (1.7.0-16898) 
I'll update to 1.8 when I get Wifi ;)

**Comment by Wikunia** [comment]
Oh maybe you can send me the file and the position where you tested it. Thanks in advance and sorry for the inconvenience.

**Comment by Wikunia** [comment]
Any news @Eugene-Musika ?
