### ISSUE TITLE
ES 2015 JSDoc not supported

### ISSUE THREAD

**Issue by nextgensparx** [Wikunia/brackets-QuickDocsJS#26]
ES 2015 specification classes are not supported. This is despite [JSDoc supporting them](http://usejsdoc.org/howto-es2015-classes.html). The default examples don't work saying **No Quick Docs available for current cursor position**

**Comment by Wikunia** [comment]
Hi @nextgensparx can you install the newest version 1.6.10 using install from url?
I used:
```
/** Class representing a point. */
module.exports = class Point {
    /**
     * Create a point.
     * @param {number} x - The x value.
     * @param {number} y - The y value.
     */
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }

    /**
     * Get the x value.
     * @return {number} The x value.
     */
    getX() {
        return this.x;
    }

    /**
     * Get the y value.
     * @return {number} The y value.
     */
    getY() {
        return this.y
    }

    /**
     * Convert a string containing two comma-separated numbers into a point.
     * @param {string} str - The string containing two comma-separated numbers.
     * @return {Point} A Point object.
     */
    static fromString(str) {
        // ...
    }
}
```

```
var Point = require('./point.js');

var p = new Point(1,2);
console.log(p.getX(),p.getY());
```
to check it and it works for me.

**Comment by nextgensparx** [comment]
@Wikunia It does not work for me. I tried it with my code and it just froze up the editor completely.

When I tried it with the code above (I modified it to be in one file) it threw this error:

> main.js:262 Uncaught TypeError: Cannot read property 'replace' of undefinedsendToInlineViewer @ main.js:262inlineProvider @ main.js:83_openInlineWidget @ /editor/EditorManager.js:244_toggleInlineWidget @ /editor/EditorManager.js:309(anonymous function) @ /editor/EditorManager.js:798Command.execute @ /command/CommandManager.js:93execute @ /command/CommandManager.js:287executeCommand @ /utils/ShellAPI.js:62

This was after pressing Ctrl+K on the Point constructor. `getX` and `getY` seem to work, however. 
Pressing Ctrl+K on `class Point` froze the editor.

**Comment by Wikunia** [comment]
Hi @nextgensparx thanks. It should work now.

**Comment by siphomateke** [comment]
@Wikunia Still the same behavior.

**Comment by Wikunia** [comment]
I have the following file:
```
/** Class representing a point. */
class Point {
    /**
     * Create a point.
     * @param {number} x - The x value.
     * @param {number} y - The y value.
     */
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }

    /**
     * Get the x value.
     * @return {number} The x value.
     */
    getX() {
        return this.x;
    }

    /**
     * Get the y value.
     * @return {number} The y value.
     */
    getY() {
        return this.y
    }

    /**
     * Convert a string containing two comma-separated numbers into a point.
     * @param {string} str - The string containing two comma-separated numbers.
     * @return {Point} A Point object.
     */
    static fromString(str) {
        // ...
    }
}

var p = new Point(1,2);
console.log(p.getX(),p.getY());
```
If I have the cursor on 'class' => I get nothing (not even a No QuickDocs available, I can't fix that atm :/)
Cursor on Point (after class) => No QuickDocs availabe (I think that's okay because nobody should click there)
Cursor on Point (after new) => I get the constructor docs (since 1.6.10)
Cursor on getX or getY => I get the correct docs for getX and getY respectively.

Do you have the same behavior?

**Comment by siphomateke** [comment]
@Wikunia It seems brackets was corrupt or something. I did a fresh install and it now works as you have described.

**Comment by Wikunia** [comment]
Perfect @nextgensparx
